//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by main.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDB_BACKGROUND                  129
#define IDB_CANCEL                      130
#define IDB_CANCEL1                     131
#define IDC_NORMAL                      132
#define IDC_HAND                        133
#define IDB_INDEX                       134
#define IDB_INDEX1                      135
#define IDB_SORT                        136
#define IDB_SORT1                       137
#define IDB_USE                         138
#define IDB_USE1                        139
#define IDD_LOGO_DIALOG                 140
#define IDB_LOGO                        142
#define IDB_LOGO1                       143
#define IDB_RESET                       144
#define IDB_RESET1                      145
#define IDC_EDIT                        146
#define IDB_LCANCEL                     147
#define IDB_LCANCEL1                    148
#define IDB_LMIN                        149
#define IDB_LMIN1                       150
#define IDB_REGIT                       151
#define IDB_REGIT1                      152
#define IDB_BACKLOGO                    153
#define IDD_REGISTER_DLG                154
#define IDB_REGISTER                    157
#define IDD_BORROW_DLG                  160
#define IDD_RETURN_DLG                  161
#define IDB_ADDNEW                      162
#define IDB_ADDNEW1                     163
#define IDB_BORROW                      169
#define IDB_BORROW1                     170
#define IDB_QUERY                       171
#define IDB_QUERY1                      172
#define IDB_RETURN                      173
#define IDB_RETURN1                     174
#define IDB_READ                        175
#define IDB_READ1                       176
#define IDR_NORMAL1                     178
#define IDD_DATA                        179
#define IDD_SET_DLG                     182
#define IDB_DLGBACK                     184
#define IDI_MAIN                        186
#define IDB_MCACEL                      190
#define IDB_MCACEL1                     191
#define IDB_MMIN                        194
#define IDB_MMIN1                       195
#define IDC_TEXTPLACE                   1001
#define IDC_TEXTUSER                    1002
#define IDC_CANCEL                      1003
#define IDC_INDEX                       1004
#define IDC_SORT                        1005
#define IDC_USE                         1006
#define IDC_LOGO                        1008
#define IDC_RESET                       1009
#define IDC_USENAME                     1010
#define IDC_PASSWORD                    1011
#define IDC_CHECK                       1012
#define IDC_RADIO1                      1013
#define IDC_RADIO2                      1014
#define IDC_MIN                         1016
#define IDC_LCANCEL                     1017
#define IDC_REGISTER                    1019
#define IDC_BORROWID                    1020
#define IDC_MYNAME                      1021
#define IDC_PASSTWO                     1023
#define IDC_NEWSADD                     1032
#define IDC_BORROW_BOOK                 1033
#define IDC_RETURNBOOK                  1034
#define IDC_READ                        1040
#define IDC_SAVE_DATA                   1041
#define IDC_READ2                       1041
#define IDC_QUERY_TEXT                  1043
#define IDC_QUERY_OK                    1044
#define IDC_TIME                        1046
#define IDC_EDIT1                       1047
#define IDC_EDIT2                       1048
#define IDC_DATA_READ                   1049
#define IDC_DATA_BOOK                   1050
#define IDC_COMBO1                      1051
#define IDC_BOOK_DATA                   1052
#define IDC_RETURN_BOOK                 1053
#define IDC_EDIT3                       1054
#define IDC_EDIT4                       1055
#define IDC_PAYOFF                      1056
#define IDC_SELECT_COMB                 1057
#define IDC_BOOK                        1058
#define IDC_DATA_GRID                   1059
#define IDC_DATA                        1060
#define IDC_SAVE                        1061
#define IDC_MENEY                       1061
#define IDC_DELETE                      1062
#define IDC_LOOK_HAVE                   1062
#define IDC_CHNIA                       1063
#define IDC_CLASS                       1064
#define IDC_BOOK_CLASS2                 1065
#define IDC_COMBO2                      1065
#define IDC_SET                         1066
#define IDC_COMBO3                      1066
#define IDC_MINIBOX                     1067
#define IDC_CANCELBOX                   1068
#define IDC_DAY                         1069
#define IDC_CHNIA2                      1069
#define IDC_MONEY                       1070
#define IDC_USEID                       1070
#define IDC_BUTTON3                     1071
#define IDC_SERCH                       1071
#define IDC_LOOK_HAVE2                  1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
